export const COMPANY = {
  name: "Ship Smart Solutions",
  tagline: "Ship Smarter with Us",
  phone: "+1 (832) 951-2823",
  phoneHref: "tel:+18329512823",
  email: "usman@elitesolutionscpa.com",
  emailHref: "mailto:usman@elitesolutionscpa.com",
  address: "650 E Diehl Rd, Naperville IL, 60563",
  coverage: "All 48 contiguous US states",
  stats: {
    onTimeRate: "99%+",
    operations: "24/7",
    warehouseSpace: "3.7M+",
    truckloadsPerMonth: "500+",
    totalAssets: "3,600+",
    unitsFulfilledPerMonth: "15M+",
  },
  services: [
    "Dedicated 53' Reefers",
    "Dedicated 53' Dry Vans",
    "Specialized Open Deck",
  ],
  clients: [
    "Amazon",
    "FedEx",
    "Walmart",
    "Costco",
    "TDU Tires",
    "Moesle Meat",
  ],
} as const
